### PR TITLE
PHP 7.2 deprecation fixes

### PR DESCRIPTION
**Pull request by pbek**

### CODE REVIEW

**Comment by gggeek** [comment]
Sorry if I am oot, but I thought that the correct way of fixing this problem is to leave in the old-style constructor, and in it simply leave a call to `__construct($etc...)`.

This because
- php will call only __construct when going via `new()`
- you might break 3rd party php code that relies on calling the old-named constructor

**Comment by gggeek** [comment]
Old code never dies ;-P

Of course in your cleanup PR you should replace all usages of the old constructors, but you still have to keep them in, least you break compatibility for all existing zombie code

**Comment by andrerom** [comment]
@gggeek is right here, but we have mostly only taken that approach in legacy kernel when we know a class is extended in other community extensions.

In extensions not typically extended we have normally just fixed the name, and if constructor is empty we typically remove it.

I don't have strong opinions here. @emodric / @wizhippo ?

**Comment by andrerom** [comment]
That said, as I intend to cherry pick these fixes to 5.3 so we don't need to introduce new feature releases of these extensions, it's probably safest if we do it the ultra safe way.

**Comment by pbek** [comment]
I took over the changes from #11.

**Comment by emodric** [comment]
I agree with @gggeek that there is much zombie code out there with which we need to preserve BC (at least in legacy kernel), but IMO, that applies only to official extension points: data types, workflows, eZPersistentObject, edit handlers, and so on.

In this case, how likely is that someone extended `eZPaEx` class? Unless it is an officially supported extension point, I think we can go with the new constructor only, without keeping the old one.

**Comment by andrerom** [comment]
Ok with that definition @gggeek ?

**Comment by gggeek** [comment]
Tbh I would still prefer to go the 'clean / compatible' route for *every* class constructor as:

a) there was never a proper separation between public and private API in ez4, so developers extended  whatever they needed

b) adopting the same pattern for updated constructors across all classes, both for the kernel and for the more obscure extensions seems to follow the pattern of least surprise for both the people doing PR reviews as well as developers still on legacy

c) it's not like this entails a huge amount of additional complexity / noise anyway. 1 method (3 php lines) per class

**Comment by andrerom** [comment]
@pbek Are you ok with doing the suggested change? See this for example on how it is done:
https://github.com/ezsystems/ezpublish-legacy/blob/master/kernel/classes/ezpersistentobject.php#L60-L67

**Comment by pbek** [comment]
Done

**Comment by andrerom** [comment]
@emodric you approve? :)

**Comment by andrerom** [comment]
Thanks a lot @pbek, @gggeek and @emodric !
Out on https://github.com/ezsystems/ezmbpaex/releases/tag/v5.3.3

**Pull request merged**
